# Spring Boot Application Properties
spring.application.name=Bin Collection Checker
server.port=8080
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
